### ISSUE TITLE
bug: don't works for songs with a title containing "*"

### ISSUE THREAD

**Issue by Hunam6** [d-fi/d-fi-core#1]
My code is the "simple example to download tracks" with `660818262` for `song_id`.

Error:
```typescript
fs.js:476
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'On vient gâcher tes classiques n*7.mp3'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at file:///C:/Users/eliet/Desktop/nodetesting/index.js:24:4
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'On vient gâcher tes classiques n*7.mp3'
}
```

**Comment by sayem314** [comment]
I’m assuming you are on windows? Windows doesn’t allow certain characters in filename. You are supposed to handle that on your side. It’s a core module, it only fetches the data. File system manipulation is not something it will do. You can use some sanitizers packager as well to replace filenames. And if you just want to download songs without creating a program you can take a look at `d-fi` package instead.

**Comment by Hunam6** [comment]
Oh okay, thanks!
